# Generated by Django 5.2.2 on 2025-06-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='city',
        ),
        migrations.AddField(
            model_name='student',
            name='marks',
            field=models.FloatField(default=11),
            preserve_default=False,
        ),
    ]
